Feature/v1.0.0
creativetimofficial/material-tailwind-dashboard-react pull request #1
Opened 2021-04-14 12:59 UTC by sajadevo

Dashboard design for Material Tailwind

2021-04-27 09:00 UTC, EINazare requested changes
`npm install` throws a couple of warnings:

<img width="637" alt="Screen Shot 2021-04-27 at 11 59 21 AM" src="https://user-images.githubusercontent.com/26245512/116215190-1ebf2e00-a750-11eb-85e3-86b4c5953c49.png">

And `npm start` does not work:

<img width="635" alt="Screen Shot 2021-04-27 at 11 59 38 AM" src="https://user-images.githubusercontent.com/26245512/116215251-2a125980-a750-11eb-970b-30068324941f.png">

2021-05-06 12:15 UTC, sajadevo commented on public/index.html
> +        <link rel="preconnect" href="https://fonts.gstatic.com" />
Its the script that we need to use the material icons font

2021-05-06 12:19 UTC, EINazare commented on public/index.html
> +        <link rel="preconnect" href="https://fonts.gstatic.com" />
Hello dude. I was curios as to what does 
```
<link rel="preconnect" href="https://fonts.gstatic.com" />
```
this link do?
The idea is, that in browser, I cannot navigate to it: https://fonts.gstatic.com/, it gives me a 404 page.

2021-05-06 12:45 UTC, sajadevo commented on public/index.html
> +        <link rel="preconnect" href="https://fonts.gstatic.com" />
I checked it and in the new version of material icons they remove this link it was from the previous one I remove it and now we don't have anything like this: <link rel="preconnect" href="https://fonts.gstatic.com" />

2021-06-02 07:14 UTC, closed without merging

2021-06-03 12:15 UTC, groovemen approved these changes